/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.Color;

/**
 *
 * @author javie
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logobg = new javax.swing.JLabel();
        logoname = new javax.swing.JLabel();
        citybg = new javax.swing.JLabel();
        registerTxt = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JLabel();
        nombrecompletoTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        correoTxt = new javax.swing.JLabel();
        correoelecTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        nombreTxt1 = new javax.swing.JLabel();
        nombrecompletoTxt1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        correoTxt1 = new javax.swing.JLabel();
        correoelecTxt1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        contraseñatext = new javax.swing.JLabel();
        passTxt1 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        tarjetaTxt = new javax.swing.JLabel();
        tarjetaTxt2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        diaTxt = new javax.swing.JLabel();
        diaTxt2 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        mesTxt = new javax.swing.JLabel();
        mesTxt2 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        anoTxt = new javax.swing.JLabel();
        anoTxt2 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        cvvTxt = new javax.swing.JLabel();
        cvvTxt2 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        promoTxt = new javax.swing.JLabel();
        promoTxt2 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        notaTxt = new javax.swing.JLabel();
        panelReg = new javax.swing.JPanel();
        labelReg = new javax.swing.JLabel();
        loginAccess = new javax.swing.JLabel();
        selectComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 236, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logobg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel1.add(logobg, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 210, 210));

        logoname.setFont(new java.awt.Font("Noto Sans Condensed ExtraBold", 0, 36)); // NOI18N
        logoname.setForeground(new java.awt.Color(255, 248, 239));
        logoname.setText("JAVABNB");
        jPanel1.add(logoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 150, 60));

        citybg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/city.png"))); // NOI18N
        jPanel1.add(citybg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 360, 650));

        registerTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 36)); // NOI18N
        registerTxt.setText("REGISTRO");
        jPanel1.add(registerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        nombreTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        nombreTxt.setText("NOMBRE COMPLETO*");
        jPanel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        nombrecompletoTxt.setBackground(new java.awt.Color(255, 236, 217));
        nombrecompletoTxt.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        nombrecompletoTxt.setBorder(null);
        nombrecompletoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecompletoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nombrecompletoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 20));

        correoTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        correoTxt.setText("CORREO ELECTRÓNICO*");
        jPanel1.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 20));

        correoelecTxt.setBackground(new java.awt.Color(255, 236, 217));
        correoelecTxt.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        correoelecTxt.setBorder(null);
        correoelecTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoelecTxtActionPerformed(evt);
            }
        });
        jPanel1.add(correoelecTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 180, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 180, 20));

        nombreTxt1.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        nombreTxt1.setText("TELÉFONO*");
        jPanel1.add(nombreTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        nombrecompletoTxt1.setBackground(new java.awt.Color(255, 236, 217));
        nombrecompletoTxt1.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        nombrecompletoTxt1.setBorder(null);
        nombrecompletoTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecompletoTxt1ActionPerformed(evt);
            }
        });
        jPanel1.add(nombrecompletoTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 180, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, 20));

        correoTxt1.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        correoTxt1.setText("DNI*");
        jPanel1.add(correoTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, 20));

        correoelecTxt1.setBackground(new java.awt.Color(255, 236, 217));
        correoelecTxt1.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        correoelecTxt1.setBorder(null);
        correoelecTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoelecTxt1ActionPerformed(evt);
            }
        });
        jPanel1.add(correoelecTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 180, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 180, 20));

        contraseñatext.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        contraseñatext.setText("CONTRASEÑA*");
        jPanel1.add(contraseñatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 30));

        passTxt1.setBackground(new java.awt.Color(255, 236, 217));
        passTxt1.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        passTxt1.setBorder(null);
        passTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxt1MousePressed(evt);
            }
        });
        jPanel1.add(passTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 180, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, 10));

        tarjetaTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        tarjetaTxt.setText("TARJETA DE CRÉDITO*");
        jPanel1.add(tarjetaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 20));

        tarjetaTxt2.setBackground(new java.awt.Color(255, 218, 181));
        tarjetaTxt2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        tarjetaTxt2.setBorder(null);
        tarjetaTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaTxt2ActionPerformed(evt);
            }
        });
        jPanel1.add(tarjetaTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 180, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 180, 10));

        diaTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        diaTxt.setText("DÍA:");
        jPanel1.add(diaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 20));

        diaTxt2.setBackground(new java.awt.Color(255, 218, 181));
        diaTxt2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        diaTxt2.setBorder(null);
        diaTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTxt2ActionPerformed(evt);
            }
        });
        jPanel1.add(diaTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 50, 20));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 50, 10));

        mesTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        mesTxt.setText("MES:");
        jPanel1.add(mesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, 20));

        mesTxt2.setBackground(new java.awt.Color(255, 218, 181));
        mesTxt2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        mesTxt2.setBorder(null);
        mesTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesTxt2ActionPerformed(evt);
            }
        });
        jPanel1.add(mesTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 50, 20));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 50, 10));

        anoTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        anoTxt.setText("AÑO:");
        jPanel1.add(anoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, 20));

        anoTxt2.setBackground(new java.awt.Color(255, 218, 181));
        anoTxt2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        anoTxt2.setBorder(null);
        anoTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoTxt2ActionPerformed(evt);
            }
        });
        jPanel1.add(anoTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 50, 20));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 50, 10));

        cvvTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        cvvTxt.setText("CVV:");
        jPanel1.add(cvvTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, 20));

        cvvTxt2.setBackground(new java.awt.Color(255, 218, 181));
        cvvTxt2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        cvvTxt2.setBorder(null);
        cvvTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTxt2ActionPerformed(evt);
            }
        });
        jPanel1.add(cvvTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 50, 20));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 50, 10));

        promoTxt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        promoTxt.setText("CÓDIGO PROMOCIONAL*");
        jPanel1.add(promoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        promoTxt2.setBackground(new java.awt.Color(255, 236, 217));
        promoTxt2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        promoTxt2.setBorder(null);
        promoTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoTxt2ActionPerformed(evt);
            }
        });
        jPanel1.add(promoTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 180, 20));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 180, 20));

        jPanel2.setBackground(new java.awt.Color(255, 218, 181));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 280, 180));

        notaTxt.setForeground(new java.awt.Color(102, 102, 102));
        notaTxt.setText("Nota: se deben rellenar todos los campos obligatorios (marcados con *)");
        jPanel1.add(notaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        panelReg.setBackground(new java.awt.Color(255, 153, 102));

        labelReg.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 14)); // NOI18N
        labelReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReg.setText("REGISTRARSE");
        labelReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRegMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelRegMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRegLayout = new javax.swing.GroupLayout(panelReg);
        panelReg.setLayout(panelRegLayout);
        panelRegLayout.setHorizontalGroup(
            panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRegLayout.setVerticalGroup(
            panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelReg, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panelReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 150, 40));

        loginAccess.setFont(new java.awt.Font("Noto Sans SemiCondensed", 0, 14)); // NOI18N
        loginAccess.setForeground(new java.awt.Color(217, 110, 57));
        loginAccess.setText("¿Ya tienes cuenta? Inicia sesión");
        loginAccess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginAccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAccessMouseClicked(evt);
            }
        });
        jPanel1.add(loginAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        selectComboBox.setBackground(new java.awt.Color(255, 153, 102));
        selectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione entre:", "Particular", "Anfitrión" }));
        selectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(selectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrecompletoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecompletoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecompletoTxtActionPerformed

    private void correoelecTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoelecTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoelecTxtActionPerformed

    private void nombrecompletoTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecompletoTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecompletoTxt1ActionPerformed

    private void correoelecTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoelecTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoelecTxt1ActionPerformed

    private void passTxt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxt1MousePressed
        if(String.valueOf(passTxt1.getPassword()).equals("*************")){
            passTxt1.setText("");
            passTxt1.setForeground(Color.black);
        }
       

    }//GEN-LAST:event_passTxt1MousePressed

    private void tarjetaTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaTxt2ActionPerformed

    private void diaTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaTxt2ActionPerformed

    private void mesTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesTxt2ActionPerformed

    private void anoTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoTxt2ActionPerformed

    private void cvvTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTxt2ActionPerformed

    private void promoTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promoTxt2ActionPerformed

    private void labelRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegMouseClicked
       
    }//GEN-LAST:event_labelRegMouseClicked

    private void labelRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegMouseEntered
        panelReg.setBackground(new Color(255,191,98));
    }//GEN-LAST:event_labelRegMouseEntered

    private void labelRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegMouseExited
        panelReg.setBackground(new Color(255, 153, 102));
    }//GEN-LAST:event_labelRegMouseExited

    private void labelRegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelRegMousePressed

    private void loginAccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAccessMouseClicked
        Sesion abrir = new Sesion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginAccessMouseClicked

    private void selectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectComboBoxActionPerformed
        String selectedOption = (String) selectComboBox.getSelectedItem();
        if (selectedOption.equals("Particular")) {
            mesTxt2.setVisible(true);
            diaTxt.setVisible(true);
            diaTxt2.setVisible(true);
            mesTxt.setVisible(true);
            anoTxt2.setVisible(true);
            anoTxt.setVisible(true);
            cvvTxt2.setVisible(true);
            cvvTxt.setVisible(true);
            promoTxt2.setVisible(true);
            jSeparator6.setVisible(true);
            jSeparator7.setVisible(true);
            jSeparator8.setVisible(true);
            jSeparator9.setVisible(true);
            jSeparator10.setVisible(true);
            jSeparator11.setVisible(true);
            jPanel2.setVisible(true);

            tarjetaTxt2.setVisible(true);
            tarjetaTxt.setVisible(true);
            promoTxt.setVisible(true);

        } else {
            mesTxt2.setVisible(false);
            diaTxt.setVisible(false);
            diaTxt2.setVisible(false);
            mesTxt.setVisible(false);
            anoTxt2.setVisible(false);
            anoTxt.setVisible(false);
            cvvTxt2.setVisible(false);
            cvvTxt.setVisible(false);
            promoTxt2.setVisible(false);
            jSeparator6.setVisible(false);
            jSeparator7.setVisible(false);
            jSeparator8.setVisible(false);
            jSeparator9.setVisible(false);
            jSeparator10.setVisible(false);
            jSeparator11.setVisible(false);
            jPanel2.setVisible(false);

            tarjetaTxt2.setVisible(false);
            tarjetaTxt.setVisible(false);
            promoTxt.setVisible(false);

        }
    }//GEN-LAST:event_selectComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoTxt;
    private javax.swing.JTextField anoTxt2;
    private javax.swing.JLabel citybg;
    private javax.swing.JLabel contraseñatext;
    private javax.swing.JLabel correoTxt;
    private javax.swing.JLabel correoTxt1;
    private javax.swing.JTextField correoelecTxt;
    private javax.swing.JTextField correoelecTxt1;
    private javax.swing.JLabel cvvTxt;
    private javax.swing.JTextField cvvTxt2;
    private javax.swing.JLabel diaTxt;
    private javax.swing.JTextField diaTxt2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelReg;
    private javax.swing.JLabel loginAccess;
    private javax.swing.JLabel logobg;
    private javax.swing.JLabel logoname;
    private javax.swing.JLabel mesTxt;
    private javax.swing.JTextField mesTxt2;
    private javax.swing.JLabel nombreTxt;
    private javax.swing.JLabel nombreTxt1;
    private javax.swing.JTextField nombrecompletoTxt;
    private javax.swing.JTextField nombrecompletoTxt1;
    private javax.swing.JLabel notaTxt;
    private javax.swing.JPanel panelReg;
    private javax.swing.JPasswordField passTxt1;
    private javax.swing.JLabel promoTxt;
    private javax.swing.JTextField promoTxt2;
    private javax.swing.JLabel registerTxt;
    private javax.swing.JComboBox<String> selectComboBox;
    private javax.swing.JLabel tarjetaTxt;
    private javax.swing.JTextField tarjetaTxt2;
    // End of variables declaration//GEN-END:variables
}
