/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.Color;


/**
 *
 * @author javie
 */
public class Sesion extends javax.swing.JFrame {

    

    /**
     * Creates new form Sesion
     */
     public Sesion() {
        initComponents();
        errorLabel.setVisible(false);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logobg = new javax.swing.JLabel();
        logoname = new javax.swing.JLabel();
        citybg = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        logoname2 = new javax.swing.JLabel();
        logintext = new javax.swing.JLabel();
        usuariotext = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contraseñatext = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        passtxt = new javax.swing.JPasswordField();
        panelAcess = new javax.swing.JPanel();
        labelAcess = new javax.swing.JLabel();
        privacyAccess = new javax.swing.JLabel();
        registerAccess1 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 236, 217));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logobg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        bg.add(logobg, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 210, 210));

        logoname.setFont(new java.awt.Font("Noto Sans Condensed ExtraBold", 0, 36)); // NOI18N
        logoname.setForeground(new java.awt.Color(255, 248, 239));
        logoname.setText("JAVABNB");
        bg.add(logoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 150, 60));

        citybg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/city.png"))); // NOI18N
        bg.add(citybg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 360, 650));

        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favicon.png"))); // NOI18N
        bg.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 70));

        logoname2.setFont(new java.awt.Font("Noto Sans ExtraBold", 0, 36)); // NOI18N
        logoname2.setForeground(new java.awt.Color(255, 153, 102));
        logoname2.setText("JavaBnB");
        bg.add(logoname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, 50));

        logintext.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 36)); // NOI18N
        logintext.setText("INICIAR SESIÓN");
        bg.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        usuariotext.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        usuariotext.setText("USUARIO");
        bg.add(usuariotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        usertxt.setBackground(new java.awt.Color(255, 236, 217));
        usertxt.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        usertxt.setForeground(new java.awt.Color(153, 153, 153));
        usertxt.setText("Ingrese su nombre de usuario");
        usertxt.setBorder(null);
        usertxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usertxtMousePressed(evt);
            }
        });
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        bg.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 450, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 450, 10));

        contraseñatext.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        contraseñatext.setText("CONTRASEÑA");
        bg.add(contraseñatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 450, 10));

        passtxt.setBackground(new java.awt.Color(255, 236, 217));
        passtxt.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        passtxt.setForeground(new java.awt.Color(153, 153, 153));
        passtxt.setText("*************");
        passtxt.setBorder(null);
        passtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passtxtMousePressed(evt);
            }
        });
        bg.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 442, 450, 30));

        panelAcess.setBackground(new java.awt.Color(255, 153, 102));

        labelAcess.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 14)); // NOI18N
        labelAcess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAcess.setText("ACCEDER");
        labelAcess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAcessMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAcessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAcessMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelAcessMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelAcessLayout = new javax.swing.GroupLayout(panelAcess);
        panelAcess.setLayout(panelAcessLayout);
        panelAcessLayout.setHorizontalGroup(
            panelAcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAcess, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelAcessLayout.setVerticalGroup(
            panelAcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAcess, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(panelAcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 150, 40));

        privacyAccess.setFont(new java.awt.Font("Noto Sans SemiCondensed", 0, 14)); // NOI18N
        privacyAccess.setForeground(new java.awt.Color(255, 178, 140));
        privacyAccess.setText("Política de privacidad");
        privacyAccess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        privacyAccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                privacyAccessMouseClicked(evt);
            }
        });
        bg.add(privacyAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        registerAccess1.setFont(new java.awt.Font("Noto Sans SemiCondensed", 0, 14)); // NOI18N
        registerAccess1.setForeground(new java.awt.Color(217, 110, 57));
        registerAccess1.setText("¿No tienes cuenta? Registrate");
        registerAccess1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerAccess1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerAccess1MouseClicked(evt);
            }
        });
        bg.add(registerAccess1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        errorLabel.setFont(new java.awt.Font("Noto Sans ExtraBold", 0, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("(*) El usuario o contraseña es incorrecto");
        bg.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, -1));

        jLabel1.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("¿Está en búsqueda del alojamiento de sus sueños?");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Le presentamos");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void labelAcessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAcessMouseEntered
        panelAcess.setBackground(new Color(255,191,98));
    }//GEN-LAST:event_labelAcessMouseEntered

    private void labelAcessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAcessMouseExited
        panelAcess.setBackground(new Color(255, 153, 102));
    }//GEN-LAST:event_labelAcessMouseExited

    private void usertxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertxtMousePressed
        if(usertxt.getText().equals("Ingrese su nombre de usuario")){
            usertxt.setText("");
            usertxt.setForeground(Color.black);
        }
        if(String.valueOf(passtxt.getPassword()).isEmpty()){
            passtxt.setText("*************");
            passtxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usertxtMousePressed

    private void passtxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passtxtMousePressed
        if(String.valueOf(passtxt.getPassword()).equals("*************")){
            passtxt.setText("");
            passtxt.setForeground(Color.black);
        }
        if (usertxt.getText().isEmpty()) {
            usertxt.setText("Ingrese su nombre de usuario");
            usertxt.setForeground(Color.gray);
        }
        
        
    }//GEN-LAST:event_passtxtMousePressed

    private void labelAcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAcessMouseClicked
        PrincipalCliente abrir = new PrincipalCliente();
        abrir.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_labelAcessMouseClicked

    private void labelAcessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAcessMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAcessMousePressed

    private void privacyAccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privacyAccessMouseClicked
        PoliticaPrivacidad abrir = new PoliticaPrivacidad();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_privacyAccessMouseClicked

    private void registerAccess1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerAccess1MouseClicked
        Registro abrir = new Registro();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerAccess1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel citybg;
    private javax.swing.JLabel contraseñatext;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel favicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAcess;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel logobg;
    private javax.swing.JLabel logoname;
    private javax.swing.JLabel logoname2;
    private javax.swing.JPanel panelAcess;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JLabel privacyAccess;
    private javax.swing.JLabel registerAccess1;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel usuariotext;
    // End of variables declaration//GEN-END:variables
}
